name: Testing matrix
on: [push, pull_request]

permissions:
  contents: read

jobs:
  php-versions:
    name: Lookup PHP versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
      - uses: antfroger/php-version-action@v1
        id: versions
        with:
          unstable: true # set to false (or remove the param) to exclude unreleased versions
          unsupported: false # set to true (or remove the param) to include unsupported versions

  test:
    name: Test PHP ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: php-versions

    strategy:
      matrix:
        os: [ubuntu-latest] # add more os
        php-version: ${{ fromJSON(needs.php-versions.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2

      - name: Test
        run: |
          composer install --no-interaction
          vendor/bin/phpunit --configuration phpunit.xml.dist
        
